
name: Development - run applcation

on:
  push:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy package to digitalocean
      uses: appleboy/ssh-action@master
      env:
          GITHUB_USERNAME: danni-popova
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        host: ${{ secrets.DEV_DO_DROPLET_IP }}
        username: root
        key: ${{ secrets.ADMIN_SSH_KEY }}
        script: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p "${{ secrets.DOCKER_PASSWORD }}"
          docker pull ${{ github.repository }}:latest
          docker run -d -p 8083:8083 --name ${{ github.repository }} ${{ github.repository }}
